# Package marker so venv_interpreter.bzl is loadable as
# //python_toolchain:venv_interpreter.bzl. The toolchain itself is generated
# at build time into the @venv_python repo (see MODULE.bazel), which is why
# there are no toolchain targets declared here anymore.
